#!/bin/bash
#
# Output `Hello World` on the command line
#
# Copyright © 2024 Red Hat, Inc.
# Copyright © 2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-3.0

printf "Hello World\n"
